Task manager application
akshi0515/FullStack-Training pull request #2
Opened 2024-07-12 04:20 UTC by akshi0515

Task manager application using HTML, CSS, Javascript and mock api.

2024-07-12 05:05 UTC, aakash-soni1 commented on Task Manager/CSS/style.css
> +body {
make sure that all id and class selectors are at single positions like at top or bottom of file, so that it will be easy to access

2024-07-12 05:05 UTC, aakash-soni1 commented on Task Manager/CSS/style.css
> +}
please do a proper formatting of the file

2024-07-12 05:05 UTC, aakash-soni1 commented on Task Manager/CSS/style.css
> +    color:rgb(204, 6, 6);
be consistence about the color if used hex every where don not use rgb

2024-07-12 05:05 UTC, aakash-soni1 commented on Task Manager/Javascript/apiManagement.js
> +    if (await checkDuplicateDescription(description)) {
do not use the function calling in the if conditions use variable to store the status and then put in the conditions

2024-07-19 08:33 UTC, charu625 commented on Task Manager/Typescript/utility.ts
> +    return descriptionA.localeCompare(descriptionB);
Can we use some other naming conventions for descriptionA and descriptionB

2024-07-19 08:36 UTC, charu625 commented on Task Manager/Typescript/taskManagement.ts
> +      const statusIcon = task.status ? "fa-solid fa-check" : "fa-regular fa-circle";
You can use same naming conventions for all class names.

2024-07-19 11:11 UTC, aakash-soni1 requested changes

2024-07-19 11:11 UTC, aakash-soni1 commented on .gitignore
> +*.js
keep the file formatted by giving the extra line at the end

2024-07-19 11:11 UTC, aakash-soni1 commented on .gitignore
> +*.js
Please check all comments again and fix them

2024-07-22 06:12 UTC, akshi0515 commented
I have resolved the review comments and pushed the updated code.
Kindly review it

2024-07-22 08:55 UTC, charu625 commented on Task Manager/CSS/style.css
> +@media (max-width: 600px) {
I think we can move media queries on the top of css file

2024-07-22 08:55 UTC, charu625 commented on Task Manager/Typescript/taskManagement.ts
> +  const handleEdit = (event: MouseEvent): void => {
Why return type is just void and not similar to addNewTask function i.e. Promise<void>?

2024-07-23 04:05 UTC, akshi0515 commented on Task Manager/Typescript/taskManagement.ts
> +  const handleEdit = (event: MouseEvent): void => {
As in this function, there are cases where we don't want to do anything and return directly, so the return type is void.
Also there is a updateDescription function in it which handles the promise so that has the data type as Promise<void>

2024-07-23 04:08 UTC, charu625 approved these changes

2024-07-26 03:18 UTC, aakash-soni1 approved these changes

2024-07-26 03:18 UTC, merged