Week 4 assignment
akshi0515/FullStack-Training pull request #4
Opened 2024-08-09 05:12 UTC by akshi0515

Shopping cart using redux

2024-08-21 09:40 UTC, charu625 commented on shopping-cart/src/components/Header.tsx
> +  const [isMenuOpen, setIsMenuOpen] = useState(false);
Over here we can declare it as const [isMenuOpen, setIsMenuOpen] = useState<boolean>(false);
For all other places where useState is used.

2024-08-21 09:40 UTC, charu625 commented on shopping-cart/src/components/Header.tsx
> +            <StyledNavLink to="/" onClick={handleLinkClick}>
Rather then all these StyledNavLink seperately we can use a map on an array with two different things i.e routesArray and headerTitle array I think.

2024-08-21 09:40 UTC, charu625 commented on shopping-cart/src/components/ShoppingCart.tsx
> +    if (newQuantity > 0) {
Can we reduce this if else code?

2024-08-21 09:40 UTC, charu625 commented on shopping-cart/src/components/ShoppingCart.tsx
> +    if (cartItems.length) return cartItems.reduce((total, item): number => total + item.price * item.quantity, 0);
Can we reduce it?

2024-08-21 09:40 UTC, charu625 commented on shopping-cart/src/components/ShoppingCart.tsx
> +                  <th>Image</th>
This can also be handled with map

2024-08-21 09:40 UTC, charu625 commented on shopping-cart/src/store/actions/cartAction.ts
> +  (i: number, id: number, quantity: number) =>
Try to use index for future purpose rather than i

2024-08-21 10:23 UTC, aakash-soni1 requested changes

2024-08-21 10:23 UTC, aakash-soni1 commented on shopping-cart/src/components/ProductList.tsx
> +                <ProductPrice>Rs {product.price.toFixed(2)}</ProductPrice>
Remove hard code value Rs use enum

2024-08-21 12:17 UTC, charu625 approved these changes

2024-08-22 05:14 UTC, shree-govinda reviewed
Why package and package-lock files are repeated twice. It should be single project right ?
You are planning to have multiple projects inside the same repository?

2024-08-22 05:14 UTC, shree-govinda commented on .github/workflows/build.yml
> +        run: npm ci --legacy-peer-deps
why npm ci ? why not just npm i ?
why --legacy-peer-deps  any dependency for this?
also include npm run lint in this this file

2024-08-22 05:28 UTC, akshi0515 commented on .github/workflows/build.yml
> +        run: npm ci --legacy-peer-deps
As we have all projects in one repository, each project is in a folder, so in each folder we have package.json and package-lock.json but to run husky we need package.json and package-lock.json outside of folder, so they are twice.

npm ci is used to install dependencies from the package-lock.json folder, on using npm i , build was failing on workflow pipeline, as it was not able to install dependencies properly, on local it was running

and I have used --legacy-peer-deps as there were dependency issues in eslint-typescript and prettier with the typescript latest version.

2024-08-22 06:04 UTC, akshi0515 commented on .github/workflows/build.yml
> +        run: npm ci --legacy-peer-deps
I have included npm run lint, in husky, so that the checking is done before commiting, I think that is better than checking while running the pipeline
@shree-govinda what do you think of it?

2024-08-22 07:34 UTC, shree-govinda commented on .github/workflows/build.yml
> +        run: npm ci --legacy-peer-deps
1. It is good to have all the checks (npm run build,  run run lint, npm test) in action file as sometimes people skip husky and try to push the code in hurry
2. Another use case is when user try to modify files directly on github web UI or other automated tool husky won't run. (Husky is meant to run only on local env)

 Actions files are meant to catch and block users from merging by any means

2024-08-22 07:39 UTC, akshi0515 commented on .github/workflows/build.yml
> +        run: npm ci --legacy-peer-deps
Ok, shree got it, will update the actions

2024-08-22 08:20 UTC, aakash-soni1 approved these changes

2024-08-22 14:15 UTC, shree-govinda approved these changes

2024-08-23 04:12 UTC, merged